package com.company;

public class Main {

    public static void main(String[] args) {
	// write your code here
       //Part3.findAllGenes("QWETREATGFDSEFVCDWERTTAAQWETREUYTATGWERSDFTAAOOOAAAATGTAAQWETREATGFDSEFVCDWERTTAAQWETREUYTATGWERSDFTAAOOOAAAATGTAAQWETREATGFDSEFVCDWERTTAAQWETREUYTATGWERSDFTAAOOOAAAATGTAA");
       //Part3.findAllGenes("QWETREATGFDSEFVCDWERTTAAQWETREUYTATGWERSWERSDFTAAODFTAAOOOAAAATGTAARTTGAQWTTGAQWETREUYT");
       //Part3.findAllGenes("QWETREATGFDSEFVCDWERTTGAQWETREUYTATWETREATGFDSEFVCDWERTTAAQWETREUYTATGWERSDFTAAOOOAAAATGTAAQWETREATGFDSEFVCDWERTTAAQWETREUYTATGWERSDFTAAOOOAAAATGTAAQWETREGWERWERTTDWERTTAAQWETREUYTATGWERSWERSDFTAAODFTAGAQTTAAQWETREUYWETSDFTAAOOOAAAARRTTGAQWTTGAQWTGTAA");
       //Part3.findAllGenes("QWETREATGFDSEFVCDWERTTAAQWETREUYTATGWERSDFTAAOOOAAAATGTAAQWETREATGFDSEFVCDWERTTAAQWETREUYTATGWERSDFTAAOOOAAAATGTAAQWETREATGFDSEFVCDWERTTAAQWETREUYTATGWERSDFTAAOOOAAAATGTAA");

       Part3.countGenes("QWETREATGFDSEFVCDWERTTAAQWETREUYTATGWERSDFTAAOOOAAAATGTAAQWETREATGFDSEFVCDWERTTAAQWETREUYTATGWERSDFTAAOOOAAAATGTAAQWETREATGFDSEFVCDWERTTAAQWETREUYTATGWERSDFTAAOOOAAAATGTAA");

    }
}
